title: Document Analysis Semester Project
description: This is the Project Report for the Document Analysis Project "A Map of Reddit, Drawn from Words" by Lucas Cimerman, Lukas Mauz and Roman Lohmiller (nurleuteplaudern)
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
#  - README.md
  - Report.md

theme: jekyll-theme-minimal
